version: "3.8"

services:
  # ---- Production build ----
  dis-bot-web:
    build: .
    ports:
      - "4000:80"
    restart: always

  # ---- (Optional) Development service with hot-reload ----
  dis-bot-web-dev:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app                # sync your local code
      - /app/node_modules     # avoid overwriting modules
    ports:
      - "4000:5173"           # Vite’s dev server default port
    command: npm run dev++      # starts vite dev server
    environment:
      - CHOKIDAR_USEPOLLING=true  # in case filesystem events need polling
